baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "St. John's Orthodox Church"
theme = 'tailwind'

[params]
  description = "St. John the Baptist Orthodox Church in Toowoomba is a welcoming Orthodox Christian community serving the Darling Downs region. Join us for Divine Liturgy on Sundays and Vespers on Saturdays."
  keywords = ["Orthodox Church", "Toowoomba", "Divine Liturgy", "Orthodox Christian", "St John the Baptist", "Russian Orthodox", "ROCOR", "Darling Downs"]
  author = "St. John the Baptist Orthodox Church"
  images = ["/img/stjohn.png"]

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
    
[[menus.main]]
name = 'About Us'
pageRef = '/about'
weight = 20

# [[menus.main]]
# name = 'Schedule'
# pageRef = '/schedule'
# weight = 30

[[menus.main]]
name = 'Orthodoxy'
pageRef = '/orthodoxy'
weight = 40

[[menus.main]]
name = 'Prayer'
pageRef = '/prayer'
weight = 45

[[menus.main]]
name = 'Stewardship'
pageRef = '/stewardship'
weight = 50

# [[menus.main]]
# name = 'Contact Us'
# pageRef = '/contact'
# weight = 60
